const products = [
  { id: 101, name: "Foam Cleanser", price: 499, image: "images/cleanser.jpg" },
  { id: 102, name: "Hydrating Moisturizer", price: 599, image: "images/moisturizer.jpg" },
  { id: 103, name: "Vitamin C Serum", price: 899, image: "images/serum.jpg" },
  { id: 104, name: "Aloe Vera Gel", price: 399, image: "images/aloe.jpg" },
  { id: 105, name: "Sunscreen SPF50", price: 699, image: "images/sunscreen.jpg" },
  { id: 106, name: "Night Repair Cream", price: 749, image: "images/nightcream.jpg" },
  { id: 107, name: "Eye Gel", price: 499, image: "images/eyegel.jpg" },
  { id: 108, name: "Glow Face Oil", price: 999, image: "images/faceoil.jpg" },
  { id: 109, name: "Exfoliating Scrub", price: 449, image: "images/scrub.jpg" },
  { id: 110, name: "Charcoal Face Mask", price: 599, image: "images/charcoal.jpg" },
  { id: 111, name: "Lip Balm", price: 199, image: "images/lipbalm.jpg" },
  { id: 112, name: "Face Toner", price: 399, image: "images/toner.jpg" },
  { id: 113, name: "Peel Off Mask", price: 499, image: "images/peelmask.jpg" },
  { id: 114, name: "Body Lotion", price: 649, image: "images/bodylotion.jpg" },
  { id: 115, name: "Green Tea Cleanser", price: 549, image: "images/greentea.jpg" },
  { id: 116, name: "Rose Water Mist", price: 349, image: "images/rosewater.jpg" },
  { id: 117, name: "Niacinamide Serum", price: 799, image: "images/niacinamide.jpg" },
  { id: 118, name: "Collagen Boost Cream", price: 899, image: "images/collagen.jpg" },
  { id: 119, name: "Anti-Aging Retinol Serum", price: 999, image: "images/retinol.jpg" },
  { id: 120, name: "Hydra Sheet Mask", price: 199, image: "images/sheetmask.jpg" },
  { id: 121, name: "Face Mist", price: 349, image: "images/facemist.jpg" },
  { id: 122, name: "Under Eye Cream", price: 649, image: "images/undereye.jpg" },
  { id: 123, name: "Clay Face Mask", price: 499, image: "images/claymask.jpg" },
  { id: 124, name: "Whitening Serum", price: 899, image: "images/whitening.jpg" },
  { id: 125, name: "Vitamin E Moisturizer", price: 599, image: "images/vitamine.jpg" },
  { id: 126, name: "Pore Minimizing Toner", price: 449, image: "images/poretoner.jpg" },
  { id: 127, name: "Coconut Body Butter", price: 699, image: "images/coconutbutter.jpg" },
  { id: 128, name: "Brightening Face Cream", price: 799, image: "images/brightcream.jpg" },
  { id: 129, name: "Neem Face Wash", price: 299, image: "images/neemwash.jpg" },
  { id: 130, name: "AHA BHA Peel Solution", price: 899, image: "images/ahabha.jpg" },
  { id: 131, name: "Tea Tree Oil", price: 599, image: "images/teatree.jpg" },
  { id: 132, name: "Hydrating Face Pack", price: 499, image: "images/facepack.jpg" },
  { id: 133, name: "Turmeric Clay Mask", price: 549, image: "images/turmeric.jpg" },
  { id: 134, name: "Avocado Moisturizer", price: 649, image: "images/avocado.jpg" },
  { id: 135, name: "Rosehip Oil", price: 699, image: "images/rosehip.jpg" },
  { id: 136, name: "Caffeine Eye Serum", price: 799, image: "images/caffeineeye.jpg" },
  { id: 137, name: "Face Polisher", price: 499, image: "images/polisher.jpg" },
  { id: 138, name: "Soothing Gel Mask", price: 599, image: "images/soothingmask.jpg" },
  { id: 139, name: "Hyaluronic Acid Serum", price: 899, image: "images/hyaluronic.jpg" },
  { id: 140, name: "Detan Scrub", price: 499, image: "images/detan.jpg" },
  { id: 141, name: "Lavender Face Mist", price: 349, image: "images/lavendermist.jpg" },
  { id: 142, name: "Oatmeal Cleanser", price: 399, image: "images/oatmeal.jpg" },
  { id: 143, name: "Milk Peel Cream", price: 699, image: "images/milkpeel.jpg" },
  { id: 144, name: "Glycolic Acid Toner", price: 749, image: "images/glycolic.jpg" },
  { id: 145, name: "Beetroot Lip Scrub", price: 199, image: "images/lipscrub.jpg" },
  { id: 146, name: "Sunblock SPF70", price: 799, image: "images/sunblock.jpg" },
  { id: 147, name: "Shea Butter Lotion", price: 699, image: "images/shealotion.jpg" },
  { id: 148, name: "Cucumber Face Wash", price: 349, image: "images/cucumber.jpg" },
  { id: 149, name: "Berry Lip Tint", price: 299, image: "images/liptint.jpg" },
  { id: 150, name: "Cooling Aloe Spray", price: 399, image: "images/aloespray.jpg" },
  { id: 151, name: "Aloe Cucumber Gel", price: 449, image: "images/aloe-cucumber.jpg" },
  { id: 152, name: "Papaya Face Scrub", price: 499, image: "images/papaya-scrub.jpg" },
  { id: 153, name: "Gold Facial Kit", price: 999, image: "images/gold-kit.jpg" },
  { id: 154, name: "Chocolate Body Butter", price: 749, image: "images/choco-butter.jpg" },
  { id: 155, name: "Peach Moisturizer", price: 599, image: "images/peach-moist.jpg" },
  { id: 156, name: "Dead Sea Mud Mask", price: 799, image: "images/deadsea.jpg" },
  { id: 157, name: "Grapeseed Oil Serum", price: 699, image: "images/grapeseed.jpg" },
  { id: 158, name: "Brightening Sheet Mask", price: 199, image: "images/bright-mask.jpg" },
  { id: 159, name: "Saffron Radiance Cream", price: 849, image: "images/saffron.jpg" },
  { id: 160, name: "Licorice Toner", price: 499, image: "images/licorice.jpg" },
  { id: 161, name: "Seaweed Exfoliator", price: 549, image: "images/seaweed.jpg" },
  { id: 162, name: "Aloe Cooling Gel", price: 399, image: "images/aloe-cool.jpg" },
  { id: 163, name: "Honey Face Wash", price: 349, image: "images/honey-wash.jpg" },
  { id: 164, name: "Detoxifying Clay Pack", price: 649, image: "images/detox-pack.jpg" },
  { id: 165, name: "Vitamin B5 Serum", price: 799, image: "images/vitaminb5.jpg" },
  { id: 166, name: "Coffee Scrub", price: 499, image: "images/coffee.jpg" },
  { id: 167, name: "Orange Peel Cleanser", price: 399, image: "images/orange.jpg" },
  { id: 168, name: "Herbal Toner", price: 449, image: "images/herbal.jpg" },
  { id: 169, name: "Mint Gel Face Pack", price: 449, image: "images/mint.jpg" },
  { id: 170, name: "Rice Water Cream", price: 699, image: "images/rice.jpg" },
  { id: 171, name: "Multani Mitti Mask", price: 499, image: "images/multani.jpg" },
  { id: 172, name: "Floral Water Toner", price: 399, image: "images/floral.jpg" },
  { id: 173, name: "Pumpkin Enzyme Peel", price: 749, image: "images/pumpkin.jpg" },
  { id: 174, name: "Argan Oil Elixir", price: 899, image: "images/argan.jpg" },
  { id: 175, name: "Skin Brightening Gel", price: 649, image: "images/brightgel.jpg" },
  { id: 176, name: "Soothing Lavender Lotion", price: 599, image: "images/lavender-lotion.jpg" },
  { id: 177, name: "Tomato Acne Gel", price: 499, image: "images/tomato.jpg" },
  { id: 178, name: "Charcoal Peel Off Mask", price: 549, image: "images/charcoalpeel.jpg" },
  { id: 179, name: "Hydra Boost Mist", price: 399, image: "images/hydramist.jpg" },
  { id: 180, name: "Yogurt Brightening Pack", price: 599, image: "images/yogurt.jpg" },
  { id: 181, name: "Skin Soothing Serum", price: 749, image: "images/soothingserum.jpg" },
  { id: 182, name: "Daily Gentle Scrub", price: 449, image: "images/gentlescrub.jpg" },
  { id: 183, name: "Ultra Light Moisturizer", price: 599, image: "images/ultralight.jpg" },
  { id: 184, name: "Cica Healing Cream", price: 799, image: "images/cica.jpg" },
  { id: 185, name: "Strawberry Lip Balm", price: 199, image: "images/strawberry.jpg" },
  { id: 186, name: "SPF30 Day Cream", price: 699, image: "images/daycream.jpg" },
  { id: 187, name: "Skin Balancing Cleanser", price: 499, image: "images/balance.jpg" },
  { id: 188, name: "Blueberry Peel Mask", price: 549, image: "images/blueberry.jpg" },
  { id: 189, name: "Deep Nourish Lotion", price: 749, image: "images/nourish.jpg" },
  { id: 190, name: "Lemon Bright Mask", price: 499, image: "images/lemon.jpg" },
  { id: 191, name: "Hydrating Lip Cream", price: 299, image: "images/lipcream.jpg" },
  { id: 192, name: "SPF15 Lip Balm", price: 199, image: "images/spflip.jpg" },
  { id: 193, name: "Face Massage Oil", price: 899, image: "images/massageoil.jpg" },
  { id: 194, name: "Coconut Milk Moisturizer", price: 649, image: "images/coconutmilk.jpg" },
  { id: 195, name: "Neem & Tulsi Face Pack", price: 499, image: "images/neemtulsi.jpg" },
  { id: 196, name: "Anti-Pollution Toner", price: 599, image: "images/antipollution.jpg" },
  { id: 197, name: "SPF100 Sport Sunscreen", price: 999, image: "images/spf100.jpg" },
  { id: 198, name: "Rose Clay Mask", price: 549, image: "images/roseclay.jpg" },
  { id: 199, name: "Turmeric Face Gel", price: 399, image: "images/turmericgel.jpg" },
  { id: 200, name: "Detan Face Wash", price: 449, image: "images/detanwash.jpg" }
];
